CREATE DATABASE IF NOT EXISTS domain DEFAULT CHARACTER SET utf8mb4;

CREATE USER IF NOT EXISTS 'code_devops'@'%' IDENTIFIED BY 'ops-coffee';
GRANT ALL PRIVILEGES ON domain.* TO 'code_devops'@'%';
FLUSH PRIVILEGES;
